### ISSUE TITLE
best-effort standing rules interpreted from minutes

### ISSUE THREAD

**Issue by echarlie** [paulwalko/vpicc-constitution#10]
we'll need to read 50+ years of scanned minutes and distill some motions from them. some interesting bits I've seen thus far:

"It was mowed that the treasurer should reaort all club cash assets once every four weeks ~ passed" 1976-10-22

"The motion that would $200 to the rescue cmmt. for equipment and make $25 available after every rescue to replenish supplies was discussed. It passed. So much for consistency." - 1980-02-01

"-Jerry Redder motioned to reestablish the old post of Sargent-af-arms was passed. The President Lawrence Britt appointd (sic) John Lohner to the post.
-Nancy Moore motioned to have the officers familiar with Robert's Rule of Order." 1981-05-15

"Chuck Shorten moved that no action be taken to rescue a trip until the ETA on the signout sheet has been reached within reason for the resident's convenience. The motion was passed. There was a discussion to form a committee and a suggestion to make this and similar important policies a standard addition to every Trog" 1981-10-16

"Carol Godla made two motions which the grotto passes. The first is that nobody has the right to X use the VPI Grotto name unless he or she is a club member and has either 2/3 of the regular and associate members consent or has officers' consent" 19820312

**Comment by paulwalko** [comment]
EWONTFIX
