### ISSUE TITLE
typo in duties of publicity

### ISSUE THREAD

**Issue by echarlie** [paulwalko/vpicc-constitution#12]
https://github.com/paulwalko/vpicc-constitution/blob/04f28c49b99a5ac01fa447d369484c1452ac6924/BY-LAWS.md?plain=1#L153

this should be an itemize

**Comment by paulwalko** [comment]
Fixed by https://github.com/paulwalko/vpicc-constitution/commit/a07a6282b00a797a8a1112dd1639bef69db977ec
